name = "forestal-mt-store"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

# Sentry auto-detects Cloudflare Pages deployment version
[version_metadata]
binding = "CF_VERSION_METADATA"

[[d1_databases]]
binding = "DB"
database_name = "fmt-products-database"
database_id = "73979325-5642-4263-8146-a13f20b36ea6"

[[kv_namespaces]]
binding = "SESSION"
id = "70e2213452d243299bb8d12be49ecb87"

# R2 â€” bound via Cloudflare Pages dashboard (not wrangler)
